COLUMNS:
  fixed acidity:
    dtype: float
  volatile acidity:
    dtype: float
  citric acid:
    dtype: float
  residual sugar:
    dtype: float
  chlorides:
    dtype: float
  free sulfur dioxide:
    dtype: float
  total sulfur dioxide:
    dtype: float
  density:
    dtype: float
  pH:
    dtype: float
  sulphates:
    dtype: float
  alcohol:
    dtype: float
  quality:
    dtype: int

TARGET_COLUMN:
  name: quality