apiVersion: v1
kind: Secret
metadata:
  name: mlflow-credentials
  namespace: wine-quality
  labels:
    app: wine-quality-prediction
type: Opaque
stringData:
  MLFLOW_TRACKING_USERNAME: "KishorKumarParoi"
  MLFLOW_TRACKING_PASSWORD: "c0edb772affc440233d8431ecf491d2e577ec401"

---
apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-secret
  namespace: wine-quality
  labels:
    app: wine-quality-prediction
type: kubernetes.io/dockercfg
data:
  # Replace with your Docker registry credentials in base64 format
  # kubectl create secret docker-registry docker-registry-secret --docker-server=<your-registry> --docker-username=<username> --docker-password=<password> --docker-email=<email> -n wine-quality --dry-run=client -o yaml
  .dockercfg: eyJhdXRocyI6eyJkb2NrZXIuaW8iOnsiYXV0aCI6IiJ9fX0=
